# Generated by Django 6.0.6 on 2026-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmemo', '0007_remove_memo_execution_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='memo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='smartmemo.tag'),
        ),
    ]
